Symlink proc-macro2 src dir into proc-macro2-fallback manifest dir
Because `..` is otherwise not available to `cargo package`.

       Compiling proc-macro2-fallback v1.0.66
    error: couldn't read ../src/lib.rs: No such file or directory (os error 2)

    error: could not compile `proc-macro2-fallback` (lib) due to previous error
    error: failed to verify package tarball