Raise minimum tested compiler to rust 1.67
Required by dev-dependency on flate2.

    error: package `flate2 v1.1.0` cannot be built because it requires
    rustc 1.67.0 or newer, while the currently active rustc version is 1.63.0
    Either upgrade to rustc 1.67.0 or newer, or use
    cargo update -p flate2@1.1.0 --precise ver
    where `ver` is the latest version of `flate2` supporting rustc 1.63.0