Unbreak fuzzing build when span-locations is used
    error[E0432]: unresolved import `crate::imp::invalidate_current_thread_spans`
       --> src/lib.rs:176:9
        |
    176 | pub use crate::imp::invalidate_current_thread_spans;
        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `invalidate_current_thread_spans` in `fallback`
        |
    note: found an item that was configured out
       --> src/fallback.rs:338:8
        |
    338 | pub fn invalidate_current_thread_spans() {
        |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^